# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-09-16 11:34
from __future__ import unicode_literals

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='broadcast date')),
                ('time', models.TimeField(default=django.utils.timezone.now, verbose_name='time')),
                ('send_to_all', models.BooleanField(default=False, verbose_name='send to all')),
                ('bc_time', models.TimeField(default=django.utils.timezone.now, verbose_name='rebc time')),
                ('bc_date', models.DateField(default=django.utils.timezone.now, verbose_name='rebc date')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='comment')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='date')),
                ('time', models.TimeField(default=django.utils.timezone.now, verbose_name='time')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='date')),
                ('time', models.TimeField(default=django.utils.timezone.now, verbose_name='time')),
            ],
        ),
        migrations.CreateModel(
            name='Mentioned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='date')),
                ('time', models.TimeField(default=django.utils.timezone.now, verbose_name='time')),
            ],
        ),
        migrations.CreateModel(
            name='DirectionBroadcast',
            fields=[
                ('broadcast_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='broadcast.Broadcast')),
                ('location', models.TextField(verbose_name='current Location')),
                ('destination', models.TextField(verbose_name='destination')),
                ('additional_info', models.TextField(verbose_name='additional information')),
            ],
            bases=('broadcast.broadcast',),
        ),
        migrations.CreateModel(
            name='ImageBroadcast',
            fields=[
                ('broadcast_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='broadcast.Broadcast')),
                ('image', cloudinary.models.CloudinaryField(blank=True, default='user.png', max_length=255, verbose_name='image')),
                ('description', models.TextField()),
            ],
            bases=('broadcast.broadcast',),
        ),
        migrations.CreateModel(
            name='TextBroadcast',
            fields=[
                ('broadcast_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='broadcast.Broadcast')),
                ('message', models.TextField()),
            ],
            bases=('broadcast.broadcast',),
        ),
        migrations.AddField(
            model_name='mentioned',
            name='broadcast_m',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_mention', to='broadcast.Broadcast'),
        ),
        migrations.AddField(
            model_name='mentioned',
            name='mentionor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentionor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='like',
            name='broadcast_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_like', to='broadcast.Broadcast'),
        ),
        migrations.AddField(
            model_name='like',
            name='liker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='broadcast_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_comment', to='broadcast.Broadcast'),
        ),
        migrations.AddField(
            model_name='comment',
            name='commenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='bc_from',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bcfrom', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_broadcast_related', to=settings.AUTH_USER_MODEL),
        ),
    ]
