# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-09-17 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0002_auto_20180917_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagebroadcast',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image'),
        ),
    ]
