# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-09-01 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0008_auto_20160804_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directionbroadcast',
            name='broadcast_ptr',
        ),
        migrations.RemoveField(
            model_name='imagebroadcast',
            name='broadcast_ptr',
        ),
        migrations.RemoveField(
            model_name='like',
            name='broadcast_message',
        ),
        migrations.RemoveField(
            model_name='like',
            name='liker',
        ),
        migrations.RemoveField(
            model_name='ridebroadcast',
            name='broadcast_ptr',
        ),
        migrations.DeleteModel(
            name='DirectionBroadcast',
        ),
        migrations.DeleteModel(
            name='ImageBroadcast',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='RideBroadcast',
        ),
    ]
