# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-09-01 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0009_auto_20180901_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionBroadcast',
            fields=[
                ('broadcast_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='broadcast.Broadcast')),
                ('location', models.TextField(verbose_name='current Location')),
                ('destination', models.TextField(verbose_name='destination')),
                ('additional_info', models.TextField(verbose_name='additional information')),
            ],
            bases=('broadcast.broadcast',),
        ),
    ]
