# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-09-01 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0010_directionbroadcast'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageBroadcast',
            fields=[
                ('broadcast_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='broadcast.Broadcast')),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
            ],
            bases=('broadcast.broadcast',),
        ),
    ]
