# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-09-03 12:06
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0012_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagebroadcast',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='user.png', max_length=255, verbose_name='image'),
        ),
    ]
