# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-09-03 12:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0014_mentioned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentioned',
            old_name='broadcast_message',
            new_name='broadcast_m',
        ),
    ]
