# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-09-16 10:16
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.TextField(help_text='Required. 10 characters or fewer. Letters, numbers and @/./+/-/_ characters', unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w.@+-]+$', 32), 'Enter a valid username.', 'invalid')], verbose_name='username')),
                ('full_name', models.TextField(verbose_name='full name')),
                ('short_name', models.TextField(blank=True, verbose_name='short name')),
                ('sex', models.TextField(choices=[('Male', 'Male'), ('Female', 'Female')], verbose_name='sex')),
                ('email', models.TextField(max_length=10, unique=True, verbose_name='email address')),
                ('phone_number', models.TextField(validators=[django.core.validators.RegexValidator(re.compile('^[0-9]+$', 32), 'Only numbers are allowed.', 'invalid')], verbose_name='phone number')),
                ('user_type', models.TextField(choices=[('Driver', 'Driver'), ('Passenger', 'Passenger')], verbose_name='user type')),
                ('address', models.TextField(verbose_name='location')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_verified', models.BooleanField(default=False, help_text='Designates whether the user is a vershified user', verbose_name='user verified')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DriverInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liscence_no', models.TextField(verbose_name='liscence number')),
                ('date_issuance', models.DateField(blank=True, verbose_name='date of first issuance')),
                ('scanned', models.ImageField(blank=True, upload_to='', verbose_name="picture of driver's liscence")),
                ('confirmed', models.BooleanField(default=False, verbose_name='confirmed')),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='time')),
                ('followee', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='followee', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(default='(No Subject)')),
                ('message', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='time sent')),
                ('read', models.BooleanField(default=False, verbose_name='read')),
                ('deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.TextField(blank=True)),
                ('work', models.TextField(blank=True)),
                ('social_facebook', models.TextField(blank=True)),
                ('social_twitter', models.TextField(blank=True)),
                ('social_instagram', models.TextField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
