# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-09-16 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180916_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverinfo',
            name='scanned',
            field=models.ImageField(blank=True, upload_to='', verbose_name="picture of driver's liscence"),
        ),
    ]
