# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-09-01 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20180128_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vehiclesharing',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vehiclesharing',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='request',
            name='ride',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
        migrations.DeleteModel(
            name='VehicleSharing',
        ),
    ]
