# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-09-01 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20180901_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='user',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
