# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-09-04 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20180903_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='app.Profile'),
        ),
    ]
